name: jackson_website
description: "Jackson's Personal Website"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web: ^0.3.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.1.2
  url_launcher: ^6.2.3
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - images/

flutter_icons:
  web: true